config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :splash_screen , only: [:index]
  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    unauthenticated do
      root 'splash_screen#index',  as: :unauthenticated_root
    end
  end
  
  resources :groups do
    resources :entities
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :entities

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :entities, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password confirm_password])
    devise_parameter_sanitizer.permit(:sign_in, keys: %i[name password])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[name email password current_password])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_user
  before_action :set_group

  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.create(**entity_params, author_id: @user.id)
    @group = Group.find(params[:group_id])
    @group.entities << @entity

    if @entity.save
      redirect_to group_entities_path(@group), notice: 'Transaction has been added successfully'
    else
      flash.now[:error] = 'Transaction could not be saved, try again'
      render :new
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @entity = @group.entities.find(params[:id])
    if @entity.destroy
      redirect_to group_entities_path(@group), notice: 'Entity was successfully destroyed.'
    else
      flash.now[:error] = 'Error: Entity could not be deleted'
    end
  end

  def edit
    @group = Group.find(params[:group_id])
    @entity = @group.entities.find(params[:id])
  end

  def update
    @group = Group.find(params[:group_id])
    @entity = @group.entities.find(params[:id])
    if @entity.update(**entity_params, author_id: @user.id)
      redirect_to group_entities_path(@group), notice: 'Category has been updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_group
    @group = @user.groups.find(params[:group_id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_user, only: %i[index edit new create update destroy]
  def index
    @groups = @user.groups.all
  end

  def show
    @group = Group.find(params[:id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.create(**group_params, author_id: @user.id)

    if @group.save
      redirect_to groups_path, notice: 'Category has been added successfully'
    else
      flash.now[:error] = 'Category could not be saved, try again'
      render :new
    end
  end

  def edit
    @group = @user.groups.find(params[:id])
  end

  def update
    @group = @user.groups.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path, notice: 'Category has been updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @group = @user.groups.find(params[:id])
    if @group.destroy
      redirect_to groups_path, notice: 'Post was successfully destroyed.'
    else
      flash.now[:error] = 'Error: Post could not be deleted'
    end
  end

  private

  def set_user
    @user = current_user
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/edit.html.erb
<div class="signup">
  <h1 class="h2">Edit your Category here.</h1>
  <%= form_with model: @entity, url: group_entity_path(@group), method: :PATCH do |form| %>
    <div class="form-group">
      <%= form.label :name , "Name", class: 'text' %>
      <%= form.text_field :name, class: 'input-mid' %>
    </div>
    <div class="form-group">
      <%= form.label :amount , "Price" , class: 'text' %>
      <%= form.text_field :amount, class: 'input-mid' %>
    </div>
    <%= form.submit "Post", class: 'btn-main' %>
  <% end %>
</div>

app/views/entities/index.html.erb
  <h1 class="h2"> Transactions
  </h1>
  <span>
  <%= link_to 'Back' , groups_path, class: 'btn-mini back-btn' %>
</span>
<div class="categories-container">
<div class="flex flex-col">
<% @entities.each do |entity| %>
  <div class="category">
      <span class="item"><%= entity.name %></span>
      <span class="text item">$<%= entity.amount%></span>
    <div class="btns">
      <div class="btn-edit btn-mini"> <%= link_to "Edit", edit_group_entity_path(@group, entity), class: 'txt-white' %> <i class="fa-solid fa-pen-to-square"></i> </div>
      <div class="btn-delete btn-mini">
      <%= link_to "Delete", group_entity_path(@group, entity), class: 'txt-white', data:  { turbo_method: :delete } %> <i class="fa-solid fa-trash"></i> </div>
    </div>
  </div>
<% end %>
</div>
<div class="flex justify-center img-div">
<%= image_tag 'transaction.png'%>
</div>
</div>
<div class="fixed bottom-0 left-0 right-0 sm:mx-20 py-8 flex">
  <%= link_to 'New Transaction', new_group_entity_path(@group) ,  class: 'btn-main w-full bg-second focus:bg-green-500 hover:bg-lightgreen-700 text-white py-2 px-4 text-center font-semibold' %>
</div>

app/views/entities/new.html.erb
<div class="signup">
  <span><%= link_to 'Back', group_entities_path, class: 'back-btn btn-mini' %></span>
  <h1 class="h2">Create Transaction here.</h1>
  <%= form_with model: @entity, url: group_entities_path do |form| %>
    <div>
      <%= form.label :name , "Name", class: 'text' %>
      <%= form.text_field :name, class: 'input-mid', required: true  %>
    </div>
    <div>
      <%= form.label :amount , "Price" , class: 'text' %>
      <%= form.text_field :amount, class: 'input-mid', required: true  %>
    </div>
    <%= form.submit "Save", class: 'btn-main' %>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="signup">
  <h1 class="h2">Edit your Category here.</h1>
  <%= form_with model: @group, url: group_path(@group), method: :PATCH do |form| %>
    <div>
      <%= form.label :name , "Name", class: 'text' %>
      <%= form.text_field :name, class: 'input-mid' %>
    </div>
    <div>
      <%= form.label :icon , "Avatar" , class: 'text' %>
      <%= form.text_field :icon, class: 'input-mid' %>
      <span class="text" style="font-size:14px;">You can use any image url here!.</span>
    </div>
    <%= form.submit "Post", class: 'btn-main' %>
  <% end %>
</div>

app/views/groups/index.html.erb
<h1 class="h2">Categories</h1>
<div class="categories-container">
<div class="flex flex-col">
  <% @groups.each do |group| %>
    <div class="category">
      <div class="category-details">
        <%= image_tag group.icon, class: 'avatar icon' %>
        <span class="item">
          <%= link_to group.name, group_entities_path(group), class: 'text' %>
        </span>
        <span class="text item price">
          $<%= group.entities.reduce(0) { |sum, e| sum + e.amount } %>
        </span>
      </div>
      <div class="btn">
        <div class="btn-edit btn-mini"> <%= link_to "Edit", edit_group_path(group), class: 'txt-white' %> <i class="fa-solid fa-pen-to-square"></i> </div>
        <div class="btn-delete btn-mini"><%= link_to "Delete", group_path(group), class:'txt-white', data:  { turbo_method: :delete } %> <i class="fa-solid fa-trash"></i> </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class="img-div">
  <%= image_tag 'categories.png', class: 'img'%>
  </div>
</div>
<div class="btn-div">
  <%= link_to 'New Category', new_group_path ,  class: 'btn-main' %>
</div>

app/views/groups/new.html.erb
<div class="signup">
  <span><%= link_to 'Back', groups_path, class:'back-btn btn-mini' %></span>
  <h1 class="green">Create your Category here.</h1>
  <%= form_with model: @group, url: groups_path do |form| %>
    <div>
      <%= form.label :name , "Name", class: 'text' %>
      <%= form.text_field :name, class: 'input-mid', required: true %>
    </div>
    <div>
      <%= form.label :icon , "Avatar" , class: 'text' %>
      <%= form.text_field :icon, class: 'input-mid', required: true  %>
      <span class="text" style="font-size:14px;">You can use any image url here!.</span>
    </div>
    <%= form.submit "Save", class: 'btn-main' %>
  <% end %>
</div>

app/views/groups/show.html.erb
<h1 class="green"> Transactions</h1>
<h1>Hello</h1>
<% @entities.each do |entity| %>
  <div class="flex justify-between items-center">
  <span class="item">
          <%= entity.name, class: 'text' %>
        </span>
    <div class="btn-edit btn-mini">
      <%= link_to "Edit", edit_group_entity_path(@group, entity), class: 'txt-white' %>
      </div>
      <div class="btn-delete btn-mini">
      <%= link_to "Delete", group_entity_path(@group, entity), data:  { turbo_method: :delete }, class: 'txt-white' %>
    </div>
  </div>
<% end %>
<div class="fixed bottom-0 left-0 right-0 sm:mx-20 py-8 flex">
  <%= link_to 'New Category', new_group_entity_path(@group) ,  class: 'w-full bg-second focus:bg-green-500 hover:bg-lightgreen-700 text-white py-2 px-4 text-center font-semibold' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <%= render 'shared/navbar'%>
    <% end %>
    <main class="container mx-auto mt-5 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl px-4 md:px-6 py-3">
    <span class= 'user-name'>
      <%= @user.name %>'s Budget
    </span>
    <% if controller_name == 'entities' and action_name == 'index' %>
      <span class="user-name">
        Total Amount: $<%= @group.entities.reduce(0) { |sum, e| sum + e.amount } %>
      </span>
    <% end %>
    <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'signout' %>
  </div>
</nav>

app/views/splash_screen/index.html.erb
<div class="flex-col signup">
  <div class="budget-app">
    <h1>Budget App</h1>
  </div>
  <div class="flex-col">
    <%= link_to 'Log in', new_user_session_path , class: "btn-mid" %>
    <%= link_to 'Sign up', new_user_registration_path , class: "btn-mid" %>
  </div>
</div>